package br.com.jhonatan.entidades;

import java.io.Serializable;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Grupo generated by hbm2java
 */
@Entity
@Table(name = "grupo", schema = "personal_control")
public class Grupo implements Serializable {

	private static final long serialVersionUID = -4791353811413671619L;

	@Id
	@GeneratedValue(generator="grupo_seq", strategy=GenerationType.SEQUENCE)
	@SequenceGenerator(name="grupo_seq", sequenceName="grupo_id_grupo_seq", schema="personal_control")
	@Column(name = "id_grupo", unique = true, nullable = false, columnDefinition="bigserial")
	private Long id;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grupo")
	private Set<Despesa> despesas;
	
	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "grupos")
	private Set<Usuario> usuarios;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Set<Despesa> getDespesas() {
		return despesas;
	}

	public void setDespesas(Set<Despesa> despesas) {
		this.despesas = despesas;
	}

	public Set<Usuario> getUsuarios() {
		return usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}
	

}
