package br.com.jhonatan.entidades;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Rendimento generated by hbm2java
 */
@Entity
@Table(name = "rendimento", schema = "personal_control")
public class Rendimento implements Serializable {

	private static final long serialVersionUID = -3336005467530312440L;

	@Id
	@GeneratedValue(generator="rendimento_seq", strategy=GenerationType.SEQUENCE)
	@SequenceGenerator(name="rendimento_seq", sequenceName="rendimento_id_rendimento_seq", schema="personal_control")
	@Column(name = "id_rendimento", unique = true, nullable = false, columnDefinition="bigserial")
	private Long id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario", columnDefinition="int")
	private Usuario usuario;
	
	@Column(name = "valor", precision = 10)
	private Double valor;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Double getValor() {
		return valor;
	}

	public void setValor(Double valor) {
		this.valor = valor;
	}

}
