package br.com.jhonatan.entidades;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Rendimento generated by hbm2java
 */

@NamedQueries({
	
	@NamedQuery(name=Rendimento.CONSULTAR_RENDIMENTOS, 
			query="select sum(r.valor) from Rendimento r"),
			
	@NamedQuery(name=Rendimento.CONSULTAR_RENDIMENTOS_POR_PESSOA,
			query="select r from Rendimento r where r.nomePessoa like concat('%', ?1, '%') or ?1 is null")
	
})

@Entity
@Table(name = "rendimento", schema = "personal_control")
public class Rendimento extends BaseEntity implements Serializable {

	private static final long serialVersionUID = -3336005467530312440L;

	public static final String CONSULTAR_RENDIMENTOS = "rendimento.consultarRendimentos";

	public static final String CONSULTAR_RENDIMENTOS_POR_PESSOA = "rendimento.consultarRendimentoPorPessoa";

	@Id
	@GeneratedValue(generator="rendimento_seq", strategy=GenerationType.SEQUENCE)
	@SequenceGenerator(name="rendimento_seq", sequenceName="rendimento_id_rendimento_seq", schema="personal_control")
	@Column(name = "id_rendimento", unique = true, nullable = false, columnDefinition="bigserial")
	private Long id;
	
	@Column(name="nome_pessoa", length=100, nullable=false)
	private String nomePessoa;
	
	@Column(name = "valor", precision = 10, nullable=false)
	private Double valor;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNomePessoa() {
		return nomePessoa;
	}

	public void setNomePessoa(String nomePessoa) {
		this.nomePessoa = nomePessoa;
	}

	public Double getValor() {
		return valor;
	}

	public void setValor(Double valor) {
		this.valor = valor;
	}

}
